# Example Client Configuration
[client]
server_addr = "127.0.0.1"
server_port = 7001
token = "secret_token"
name = "my-client"
conf_d = "./conf.d"
compression = true

[client.ssl]
enable = false
verify_peer = false
# ca_file = "certs/ca.crt"

[[client.proxies]]
name = "ssh"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 22
remote_port = 6000

[[client.proxies]]
name = "web-http"
type = "http"
local_ip = "localhost" # Supports domain names now!
local_port = 8080
custom_domains = ["a.com", "b.com"]
bandwidth_limit = "1M" # Limit to 1MB/s aggregate for this proxy

[[client.proxies]]
name = "web-https"
type = "https"
local_ip = "127.0.0.1"
local_port = 8443
custom_domains = "secure.com"
